### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Estherrr1997** [s-andrews/redotable#18]
Hi,

I am using redotable for visualizing the alignment between two sharks.
After calling redotable, I open the files but I get the following error:

(base) admin_bi@GSYMK2:/media/admin_bi/DATA/Files_Esther/redotable_v1.1$ ./redotable 
CLASSPATH is : /media/admin_bi/DATA/Files_Esther/redotable_v1.1
Memory ceiling is 5120
Raw physical memory is 31977
Correcting for VM actual requested allocation for 5120 is 5120
Command is: java -Xmx2048m -Xmx5120m uk.ac.babraham.redotable.RedotableApplication 
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
	at uk.ac.babraham.redotable.utilities.ByteVector.makeLonger(ByteVector.java:96)
	at uk.ac.babraham.redotable.utilities.ByteVector.add(ByteVector.java:44)
	at uk.ac.babraham.redotable.datatypes.Sequence.addSequence(Sequence.java:82)
	at uk.ac.babraham.redotable.datatypes.SequenceCollection.addSequence(SequenceCollection.java:156)
	at uk.ac.babraham.redotable.parsers.SequenceParser.run(SequenceParser.java:74)
	at java.base/java.lang.Thread.run(Thread.java:829)

Is there a way to pass more memory into redotable?

Kind regards,
Esther

**Comment by s-andrews** [comment]
Yes, you can run ```./redotable --memory 10000``` to give you 10GB of memory - adjust that value to whatever you need and your system will handle.

**Comment by Estherrr1997** [comment]
Thank you! that fixed it :)
